config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :devices
  resources :tasks
  resources :brands
  resources :clients
  resources :device_cats
  resources :employees
  resources :orders
  resources :spares

  get 'home/' => 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :devices
  has_many :spares
end

app/models/client.rb
class Client < ActiveRecord::Base
  
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :brand
  belongs_to :device_cat
end

app/models/device_cat.rb
class DeviceCat < ActiveRecord::Base
  has_many :devices
  has_many :spares
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :post
  has_one :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client
  belongs_to :device
  belongs_to :dispatcher, class_name: 'Employee'
  belongs_to :master, class_name: 'Employee' #try scope
  belongs_to :status
  has_many :tasks
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :employees

end

app/models/spare.rb
class Spare < ActiveRecord::Base
  belongs_to :spare_cat
  belongs_to :device_cat
  belongs_to :brand
  has_and_belongs_to_many :tasks

end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :orders

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :order
  has_and_belongs_to_many :spares


end

app/models/user.rb
class User < ActiveRecord::Base
  #before_save { self.email = email.downcase }
  validates :login, presence: true, length: {maximum: 50}
  has_secure_password
  validates :password, length: {minimum: 6}
  belongs_to :employee

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all.order("title ASC")
  end

  def new

  end

  def show
    
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user
  def index
    
  end

  private
    def user_params
      params.require(:person).permit(:login, :password)
    end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
    @orders = Order.all.order("created_at DESC")
  end

  def new

  end

  def show
    
  end

  def soso
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autentification_helper.rb
module AutentificationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def pendings 
    @orders.where(status_id: 2)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def current_user= user
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt cookies[:remember_token]
    @current_user ||= User.find_by remember_token: remember_token
  end

  def sign_in user
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token #expires after 20 years
    user.update_attribute :remember_token, User.encrypt(remember_token)
    self.current_user = user
  end

  def signed_in?
    !!current_user
  end

  def sign_out
    current_user.update_attribute :remember_token, User.encrypt(User.new_remember_token)
    cookies.delete :remember_token
  end
end

app/views/layouts/_status_tabs.html.haml
.row
  %ul.nav.nav-tabs.nav-justified#tabs
    %li.current{ :role => 'presentation', :data => {tab: "all"}}
      =link_to "Все", 
    %li{ :role => 'presentation', :data => {tab: "accepted"} }
      %a{ :href =>"#" } Принят в ремонт
    %li{ :role => 'presentation', :data => {tab: "pending"}}
      %a{ :href =>"#" } Ожидает запчасть
    %li{ :role => 'presentation', :data => {tab: "repairing"} }
      %a{ :href =>"#" } В ремонте
    %li{ :role => 'presentation', :data => {tab: "remote"} }
      %a{ :href =>"#" } В удаленном СЦ
    %li{ :role => 'presentation', :data => {tab: "agreement"} }
      %a{ :href =>"#" } Согласование
    %li{ :role => 'presentation', :data => {tab: "agreed"} }
      %a{ :href =>"#" } Согласовано

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = yield :title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
          .collapse.navbar-collapse.navbar-menubuilder
            %ul.nav.navbar-nav.navbar-left
              %li
                =link_to "Заказы", orders_path

            %ul.nav.navbar-nav.navbar-right
              %li
                =link_to "Выйти", logout_path, method: 'delete'
              %li
                %a
                  %strong=current_user.login.capitalize
              



    = yield